const data = {
  nodes: [
    { id: "Python", group: 1 },
    { id: "Machine Learning", group: 1 },
    { id: "Data Science", group: 1 },
    { id: "3 years experience", group: 2 },
    { id: "Bachelor's degree in Computer Science", group: 2 },
    { id: "TensorFlow", group: 3 },
    { id: "Scikit-learn", group: 3 },
    { id: "Large Language Models (LLMs)", group: 4 },
    { id: "Generative AI", group: 4 },
    { id: "Reinforcement Learning", group: 4 },
    { id: "Computer Vision", group: 4 },
    { id: "Natural Language Processing (NLP)", group: 4 },
    { id: "Explainable AI (XAI)", group: 4 },
    { id: "MLOps", group: 4 },
    { id: "Edge AI", group: 4 },
    { id: "Federated Learning", group: 4 },
    { id: "PyTorch", group: 3 },
    { id: "Model Compression", group: 4 },
    { id: "AI Ethics", group: 4 },
    { id: "AI Security", group: 4 },
  ],
  links: [
    { source: "Python", target: "3 years experience" },
    { source: "Machine Learning", target: "3 years experience" },
    { source: "Data Science", target: "3 years experience" },
    { source: "Python", target: "Bachelor's degree in Computer Science" },
    {
      source: "Machine Learning",
      target: "Bachelor's degree in Computer Science",
    },
    { source: "Data Science", target: "Bachelor's degree in Computer Science" },
    { source: "Python", target: "TensorFlow" },
    { source: "Python", target: "Scikit-learn" },
    { source: "Machine Learning", target: "TensorFlow" },
    { source: "Machine Learning", target: "Scikit-learn" },
    { source: "Data Science", target: "TensorFlow" },
    { source: "Data Science", target: "Scikit-learn" },
    {
      source: "Large Language Models (LLMs)",
      target: "Natural Language Processing (NLP)",
    },
    { source: "Large Language Models (LLMs)", target: "Python" },
    { source: "Generative AI", target: "TensorFlow" },
    { source: "Reinforcement Learning", target: "Python" },
    { source: "Computer Vision", target: "TensorFlow" },
    { source: "Python", target: "PyTorch" },
    { source: "PyTorch", target: "Machine Learning" },
    { source: "Model Compression", target: "TensorFlow" },
    { source: "Model Compression", target: "PyTorch" },
    { source: "AI Ethics", target: "Explainable AI (XAI)" },
    { source: "AI Security", target: "MLOps" },
  ],
};

export default data;
